### ISSUE TITLE
Suggestion to add function to read the phylogenies of a BEAST2 posterior file

### ISSUE THREAD

**Issue by richelbilderbeek** [beast-dev/RBeast#1]
[olli0601's rBEAST package](https://github.com/olli0601/rBEAST) has a function to read a `.trees` file to obtain a list of posterior phylogenies. The function is called `beast2out.read.trees` and I have used it much. I suggest to add that function to this repository (with the proper acknowledgements of course).

Do I have a green light to submit a Pull Request?

**Comment by msuchard** [comment]
Hi @richelbilderbeek, Olli's tree reader looks great.  Please
- prepare a pull request
- briefly document how this function behaves differently from `OutbreakTools::read.annotated.tree()` (which I am planning on moving into `RBeast`)

Am very happy to have you and @olli0601 on-board!
