### ISSUE TITLE
Enable lintr-bot again

### ISSUE THREAD

**Issue by richelbilderbeek** [beast-dev/RBeast#12]
I'd like to enable @lintr-bot again. It was disabled in in August 2016, with the intention of cleaning up the code submitted then, which has not been done yet. As if the incentive to clean up code is lost without @lintr-bot. 

I suggest 
 * to enable @lintr-bot at August 1st 2017 
 * people (let someone) clean the code they committed

Good idea? Other suggestions?

**Comment by msuchard** [comment]
I agree.   BTW, nice interview on `CppCast`
