### ISSUE TITLE
RBeast issue -Assuming a complexity prior distribution on the number of change-points with `gammaParameter = 2`

### ISSUE THREAD

**Issue by Maglisa** [beast-dev/RBeast#16]
Hi,

It seems that there is an issue with Rbeast, it is not running today. My code worked perfectly fine the previous day but today I am getting an error . (see the error output below "=====")

* Assuming a complexity prior distribution on the number of change-points with `gammaParameter = 2`. 
*  Computing posterior parameters... Error in numeric(nTime) : invalid 'length' argument

Is this a temporally thing? Can you help?

Thank you,

**Comment by richelbilderbeek** [comment]
Hi @Maglisa, I guess this is fixed? :partying_face:
