### ISSUE TITLE
any tutorial on using of this?

### ISSUE THREAD

**Issue by liamxg** [beast-dev/RBeast#17]

**Comment by richelbilderbeek** [comment]
Hi @LiXingguangBrandonStark, thanks for the question on this rather low-use repo. Most of the repo's linked to in the README have tutorials. The best documented (note: I am the author of it, so you may question my objectivity :-) ) one is called [babette](https://github.com/ropensci/babette), that has [multiple articles and tutorials and YouTube video's about it](https://github.com/ropensci/babette#examples).

**Comment by liamxg** [comment]
thanks so much for your help. This is a great repo.

**Comment by richelbilderbeek** [comment]
@LiXingguangBrandonStark happy to help! I am always happy to chat about `babette`, send me an email if you'd enjoy that too.

Closing this Issue :+1:

**Comment by LiXingguangBrandonStark** [comment]
@richelbilderbeek yes, I am very interested about this, I will email to you, could you please tell me your email, thanks.

**Comment by richelbilderbeek** [comment]
As I am -to my surprise- no longer a member of `beast-dev`, I cannot close this Issue. I'll let the `beast-dev`-team close this Issue :-)

**Comment by richelbilderbeek** [comment]
@LiXingguangBrandonStark googling my email is simple. Try, for example, [here](https://www.richelbilderbeek.nl/Contact.htm) :-)

**Comment by LiXingguangBrandonStark** [comment]
so babette is for beast2?

**Comment by richelbilderbeek** [comment]
@LiXingguangBrandonStark babette is for BEAST2 indeed. For BEAST, I have no good suggestions.

**Comment by LiXingguangBrandonStark** [comment]
but some codes can be used for BEAST, right?

**Comment by richelbilderbeek** [comment]
@LiXingguangBrandonStark yes: the `tracerer` package reads the BEAST/BEAST2 output files and can produce the same summary statistics.

**Comment by liamxg** [comment]
thanks. you are so nice.
