### ISSUE TITLE
why cutoffs can not be set large?

### ISSUE THREAD

**Issue by liamxg** [beast-dev/RBeast#19]
<img width="739" alt="image" src="https://github.com/beast-dev/RBeast/assets/46078579/0f7cea5b-396d-46a4-b6cd-3e4781821b75">

**Comment by maxbiostat** [comment]
This message says `cutoffs` is not an argument of the `plot_glm()` function. Please email me in private and we'll figure this out.

**Comment by liamxg** [comment]
thanks, I will.
