### ISSUE TITLE
Suggestion: add function to read the parameter estimates of a BEAST2 posterior file 

### ISSUE THREAD

**Issue by richelbilderbeek** [beast-dev/RBeast#3]
I have written a function that reads a .log file to obtain a data.frame with all parameter estimates in the MCMC. I suggest to add that function to this repository.

Do I have a green light to submit a Pull Request?

**Comment by msuchard** [comment]
Sure.

**Comment by richelbilderbeek** [comment]
Added by sending a Pull Request, that got accepted.
