### ISSUE TITLE
Suggestion: add Travis CI

### ISSUE THREAD

**Issue by richelbilderbeek** [beast-dev/RBeast#4]
Travis CI is a continuous integration service that performs all kinds of checks upon a `git push`. As most of my GitHubs have this, I volunteer to add this.

To resolve this Issue I will add a script that just does most of the tests on CRAN.

In other Issues I will suggest to add more tests like (1) code coverage using [covr](https://github.com/jimhester/covr) (2) coding style using [lintr](https://github.com/jimhester/lintr) (3) use of good practices, using [goodpractice](https://github.com/mangoTheCat/goodpractice)

**Comment by msuchard** [comment]
Am all in favor of `travis`, `covr`, `lintr` and `goodpractice`.

**Comment by richelbilderbeek** [comment]
Added Travis CI. Although not all tests pass at Travis yet, I close this Issue.
