### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by richelbilderbeek** [beast-dev/RBeast#5]
A licence needs to be chosen for this package. I suggest GPL 3.0. I need a green light on this by @msuchard , as this will also affect his code. Feel free to suggest another license.

If there is a licence chosen, I will add it with pleasure.

**Comment by msuchard** [comment]
UCLA prefers the MIT license.  If this is OK with you, please go ahead.

**Comment by richelbilderbeek** [comment]
I will add the MIT license and state it is definite.

**Comment by richelbilderbeek** [comment]
Note: I set the copyright to `Marc A. Suchard, Nuno Faria, Richel Bilderbeek`, please edit where needed.
