### ISSUE TITLE
rJava and xml2 troubleshooting needed?

### ISSUE THREAD

**Issue by richelbilderbeek** [beast-dev/RBeast#6]
When I installed rJava on a local computer, I needed to do:

```
sudo apt-get install r-cran-rjava
sudo R CMD javareconf
```

It may be needed on Travis as well, this Issue is a note to self until I've found this out

**Comment by richelbilderbeek** [comment]
Note for installing `xml2` library:
```
sudo apt-get install libxml2-dev
```

**Comment by msuchard** [comment]
Here is a [.travis.yml](https://github.com/OHDSI/SqlRender/blob/master/.travis.yml) that installs `rJava`.  However, it does not use the `language: r` feature.

**Comment by richelbilderbeek** [comment]
I'll fix it :-)

**Comment by richelbilderbeek** [comment]
I guess it has been fixed...
